trigger:
  branches:
    include:
      - main  # or your working branch

variables:
  imageName: 'iwebtechno-nextjs-app'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image to ACR'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker image and push to ACR'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: 'azure-service-connection'  # Name of your Azure DevOps Service Connection to ACR
        repository: 'iwebtechno-etauhfhpcbevcac7.azurecr.io/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy image from ACR to Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to App Service using container image'
            inputs:
              azureSubscription: 'azure-service-connection'  # Same service connection
              appName: 'iwebtechno-nextjs-webapp'
              containers: 'iwebtechno-etauhfhpcbevcac7.azurecr.io/$(imageName):$(tag)'
