trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'CI/CD Service'                      # ARM service connection name
  azureContainerRegistryServiceConnection: 'iwebtechno'   # ACR service connection name
  azureContainerRegistryLoginServer: 'iwebtechno-etauhfhpcbevcac7.azurecr.io'  # ACR login server URL
  imageName: 'iwebtechno-nextjs-webapp'
  webAppName: 'iwebtechno-nextjs-webapp'
  resourceGroup: 'iWebTechno-website'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: '$(azureContainerRegistryServiceConnection)'   # service connection name
        repository: '$(azureContainerRegistryLoginServer)/$(imageName)'   # full repo path
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployWebApp
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy container to Azure Web App
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(webAppName)'
              resourceGroupName: '$(resourceGroup)'
              imageName: '$(azureContainerRegistryLoginServer)/$(imageName):latest'
