trigger:
  branches:
    include:
      - main   # or your deployment branch

variables:
  azureSubscription: 'Microsoft Azure Sponsorship'   # Set this in Azure DevOps
  azureContainerRegistry: 'iwebtechno-etauhfhpcbevcac7.azurecr.io'
  imageName: 'iwebtechno-nextjs-webapp'
  webAppName: 'iwebtechno-nextjs-webapp'
  resourceGroup: 'iWebTechno-website'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: '$(azureContainerRegistry)'
        repository: '$(azureContainerRegistry)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy container to Azure Web App
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(webAppName)'
              resourceGroupName: '$(resourceGroup)'
              imageName: '$(azureContainerRegistry)/$(imageName):latest'
